server:
  port: 8080
  servlet:
    context-path: /customer-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: 'true'
   
spring:
  application:
    name: customer-order-apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
      - id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer-order/customer-service/**
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/customer-order/order-service/**
      - id: customer-order-bff
        uri: lb://CUSTOMER-ORDER-BFF
        predicates:
          - Path=/customer-order/bff/**

#ACCOUNT: minibank-account
#APIGATEWAY: localhost
#B2BT: minibank-b2bt
#CQRS: minibank-cqrs
#CUSTOMER: minibank-customer
#EUREKA: localhost
#KAFKA: localhost
#POSTGRES: localhost
#TRANSFER: minibank-transfer